name: TestPlugin
version: 1.0.0
main: fr.joupi.api.Spigot
depend: [ ProtocolLib ]

commands:
  join:
    description: join game
  leave:
    description: leave game
  info:
    description: game info
  end:
    description: end game
  party:
    description: party command
  duel:
    description: duel command